### PR TITLE
Added Python and C# Solution

### PR DESCRIPTION
**Pull request by zpratikpathak**
Added Solution, So that it will be easier for students to see the final code and verify there progress

### CODE REVIEW

**Comment by zpratikpathak** [comment]
Added C# as well as Python Solution for 02-QnA.

**Comment by zpratikpathak** [comment]
Will Add all the solution

**Comment by ivorb** [comment]
Hi @zpratikpathak thanks for the PR. We intentionally don't publish the completed exercises to leave it as good practice for learners. The extra ` you noted is a worthwhile fix, so I'll either fix that with my next publish or you can submit a PR for that, however I'm closing this PR adding the solution.

**Comment by zpratikpathak** [comment]
okay okay,  i will raise a separate PR for `

**Pull request closed without merging**
